### PR TITLE
patch: 1.1.1

### LINKED ISSUE #16: React Admin: Corporate Devices
- The devices are not being fetched (The API request returns no response, and a `dataProvider threw an error` is logged in the console)
image

- On click of a Corporates row, a client-side exception occurs on the screen.
image

- The sidebar icons for *Corporates* needs to be changed to match the icon used on the landing page for corporate donors.

- The "CorporateDevices" list title on the Corporate Devices page needs to be changed to *Corporate Devices List*

### LINKED ISSUE #18: Certificate: Donor name appearing in two separate lines
The name of the donor is appearing broken in two separate lines in the certificate. This should appear in the same line.

### PR DESCRIPTION
**Pull request by sagar-techjoomla**
Fixes #16, Fixes #18

### CODE REVIEW

File: portal/components/react-admin/layout/verticalItem.js [hunk 1]
```diff
@@ -37,6 +37,9 @@ const Icon = (props) => {
     return <SmartphoneIcon className={props.className} />;
   if (props.type === "school")
     return <SchoolIcon className={props.className} />;
+  if(props.type === "corporate") {
+    return <span className={`material-icons corporate_fare`} style={{color:'#626D74',fontSize: '1.2rem'}} >corporate_fare</span>
```
Comment (bharatkashyap) [inline portal/components/react-admin/layout/verticalItem.js:41]: Can we follow the same style of adding icons as in `<SchoolIcon>` and `<SmarthphoneIcon>`

**Review by bharatkashyap — APPROVED** [review]

**Review by bharatkashyap — APPROVED** [review]
